spring:
  profiles:
   active: dev # 激活开发环境配置
---
server:
  port: 8002

spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config-2 #这个很重要，这在以后的服务与服务之间相互调用一般都是根据

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
#      defaultZone: http://localhost:6001/eureka
      defaultZone: http://10.7.125.123:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true
 
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    
---

server:
  port: 8002

spring:
  profiles:  prod # 开发环境
  application:
    name: microservice-product-config-2 #这个很重要，这在以后的服务与服务之间相互调用一般都是根据

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
#      defaultZone: http://localhost:6001/eureka
      defaultZone: http://10.7.125.123:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true
    
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
